### ISSUE TITLE
Any plans to support Jest?

### ISSUE THREAD

**Issue by damassi** [invertase/jet#8]
Curious if this is on the roadmap.

**Comment by yogeshthanvi** [comment]
Even i was looking for JET support for JEST

**Comment by Salakar** [comment]
Yes, will be dropping Mocha and going with Jest by default in a future release.

My time is limited on this right now though - we still heavily use this on React Native Firebase, so the project is not going anywhere - if anyone wants to take the lead on working towards v1.0.0 please let me know - otherwise, I'll get to this probably by mid-year.

**Comment by ReshmiCode** [comment]
I would definitely need jest integration to start using this project

**Comment by ivanmoskalev** [comment]
I'm actually ready to help out on this issue, and I can find some time on this weekend to start doing this. 

@Salakar please tell me if I can take this issue, and if so, what branch should I base my work on (I'm guessing, [this one](https://github.com/invertase/jet/tree/%40salakar/wip-rework))?
